### ISSUE TITLE
Game crashes when attempting to cycle weapons while no weapons are obtained.

### ISSUE THREAD

**Issue by Adk9057** [CE-Studio/SnailiadPlus#13]
**Affected Version(s)**: 0.3.0, 0.3.1, 0.3.2
**Unaffected Version(s)**: 0.1.1, 0.2.0, 0.2.1
**Affected Operating System(s)**: Windows 10 22H2 (Microsoft Windows NT Version 10.0.19045.3570)

*Untested on Mac and Linux

Steps to Reproduce:
1. Start a new save file
2. Press |Next Weapon| / |Previous Weapon|
Result: Game Crash

Processor: AMD Ryzen 3 3250U + Radeon Vega 3

https://github.com/CE-Studio/SnailiadPlus/assets/135939396/a7c1d99c-7801-412e-8b90-b2dd572258e5

**Comment by clarence112** [comment]
Fixed by [`becc8f7`](https://github.com/CE-Studio/SnailiadPlus/commit/becc8f79ff59309ffeed0779af54561d34087a17#diff-e65036fee1cff958931462d7536a02606acb134d91dd8b158421aa01ba3f1f5f)
